language: node_js
cache:
  directories:
    - ~/yarn.lock
    - ~/node_modules
notifications:
  email: false
node_js:
  - '8'
scripts:
  - yarn test
after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/